name: Triggers
on: 
  # If someone opens Pull Request (PR) to main branch
  pull_request:
    types: [opened, reopened]
    branches:
      - 'releases/**'

  # push:
  #   branches:
  #     - 'main'

  # workflow_dispatch

  # [push]                            # Triggers the workflow on every push to the repository

jobs:
  # Job name
  trigger:
    runs-on: ubuntu-latest            # Github hosted runners
    steps:
      # - name: Manual dispatch
      #   run: echo "Manually dispatched"     # The command to execute
      - name: Main branch push
        run: echo "Pushed to main branch"     # The command to execute