# name: Hello World Action
# on: workflow_dispatch                           # Triggers the workflow on every push to the repository

# jobs:
#   # Job name
#   say-hello:
#     runs-on: ubuntu-latest            # Github hosted runners
#     steps:
#       - name: Greet the world
#         id: greet
#         uses: javeed-mohd/github-actions/.github/actions/hello-world@main
#         with:
#           who-to-greet: 'Javeed'
      
#       - run: echo random-number "$RANDOM_NUMBER"
#         shell: bash
#         env:
#           RANDOM_NUMBER: ${{ steps.greet.outputs.random-number }}